# roles/launch_proxy/tasks/main.yml

- name: Run Proxy
  community.docker.docker_container:
    name: httpd
    image: l1elou/tp-devops-http-server
    ports:
      - "80:80"
    networks:
      - name: my-network
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3


