- name: Create Docker volume
  community.docker.docker_volume:
    name: db-volume  # Match volume name from Docker Compose
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
